version: '3.1'

services:
  drupal:
    image: drupal:8-apache
    ports:
      - "8080:80"
    volumes:
      - drupal-config:/var/www/html/sites/default
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_HOST=db
    restart: always
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=root
    restart: always
volumes:
  mysql-data:
    driver: local
  drupal-config:
    driver: local
  drupal-modules:
    driver: local
  drupal-profiles:
    driver: local
  drupal-themes:
    driver: local
  drupal-sites:
    driver: local
